Add insecure config to bypass unknown cert issue
aws/eks-anywhere-packages pull request #671
Opened 2022-12-06 23:18 UTC by vincentni

2022-12-07 12:42 UTC, TerryHowe requested changes

2022-12-07 12:42 UTC, TerryHowe commented on Dockerfile
>  # Build the manager binary
This docker file is not used.

2022-12-07 12:42 UTC, TerryHowe commented on pkg/artifacts/registry.go
> +	registry, err := content.NewRegistry(content.RegistryOptions{Insecure: true})
Alarm bells are going off here. Can we pass in the cert instead?

2022-12-08 03:43 UTC, vincentni commented
Close this PR as we are not rushing for Thursday's code freeze.

2022-12-08 03:43 UTC, closed without merging