Add 1.26 dev bundle support for packages
aws/eks-anywhere-packages pull request #824
Opened 2023-02-17 17:19 UTC by taneyland

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-17 17:37 UTC, jonahjon requested changes

2023-02-17 17:37 UTC, jonahjon commented on generatebundlefile/data/bundles_dev/1-26.yaml
> +          - name: 9.21.0-1.26-latest
Do these exist yet, the new Autoscaler and Metrics server versions?

2023-02-17 17:37 UTC, jonahjon commented on generatebundlefile/data/bundles_dev/1-26.yaml
> +          - name: 9.21.0-1.26-latest
If not let's hold off merging this until they do.

2023-03-10 11:53 UTC, TerryHowe commented
Done in another PR

2023-03-10 11:53 UTC, closed without merging